global:
  resolve_timeout: 5m
  slack_api_url: 'slack_api_url'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 30m
  receiver: slack-notifications

receivers:
  - name: slack-notifications
    slack_configs:
      - channel: "#alerts"
        send_resolved: false
