global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 30m
  receiver: slack-notifications

receivers:
  - name: slack-notifications
    slack_configs:
      - channel: "#alerts"
        send_resolved: false
