global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'prometheus-master.razumovsky.me:9093'

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - 'linux-target.razumovsky.me:9100'
        - 'windows-target.razumovsky.me:9182'

rule_files:
  - "cpu_alerts.yml"
