parameters:
  - name: stageName
    displayName: 'Stage name display name'
    type: string

  - name: vmImage
    displayName: 'Vm Image'
    default: 'windows-latest'
    type: string

  - name: terraformVersion
    displayName: 'Terraform Version'
    type: string
    default: 'latest'

  - name: workingDirectory
    displayName: 'Working Directory'
    type: string

  - name: storageAccount
    displayName: 'Storage Account'
    type: string

  - name: storageContainer
    displayName: 'Storage Container'
    type: string

  - name: stateFile
    displayName: 'State File'
    type: string

  - name: sasToken
    displayName: 'Sas Token'
    type: string

  - name: environment
    displayName: 'Environment'
    type: string

  - name: dependsOn
    displayName: 'Depends On'
    type: object

  - name: condition
    displayName: 'Condition'
    type: string

  - name: subscriptionId
    displayName: 'Azure Subscription Id'
    type: string

  - name: clientId
    displayName: 'Azure Client Id'
    type: string

  - name: clientSecret
    displayName: 'Azure Client Secret'
    type: string

  - name: tenantId
    displayName: 'Azure Tenant Id'
    type: string

  - name: cloudflareToken
    displayName: 'Cloudflare API token'
    default: $(library-cloudflare-token)
    type: string

  - name: shouldUpdateDnsRecords
    default: 'true'
    type: boolean
    displayName: 'Flag to update DNS records or not'

  - name: shouldConfigureAlertManager
    default: 'true'
    type: boolean
    displayName: 'Flag to update DNS records or not'

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: succeeded('${{ parameters.condition }}')
    jobs:
      - deployment: ${{ parameters.stageName }}
        displayName: ${{ parameters.stageName }}
        pool:
          vmImage: ${{ parameters.VmImage }}
        environment: ${{ parameters.environment }}
        variables:
          - name: 'TF_LOG'
            value: 'INFO'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  fetchDepth: 0

                - task: PowerShell@2
                  displayName: 'Fix encoding'
                  inputs:
                    targetType: 'inline'
                    script: |
                      Install-Module VerifyEncoding -Repository PSGallery -Scope CurrentUser -Force
                      Test-Encoding -Autofix
                    workingDirectory: ${{ parameters.workingDirectory }}
                    pwsh: true

                - download: current
                  artifact: drop

                - task: DownloadSecureFile@1
                  name: privateKey
                  displayName: "Download Private Key"
                  inputs:
                    secureFile: "id_rsa"

                - task: DownloadSecureFile@1
                  name: publicKey
                  displayName: "Download Public Key"
                  inputs:
                    secureFile: "id_rsa.pub"

                - powershell: |
                    "$(library-rdp-password)" | Set-Content -Path ./password.txt
                  displayName: 'Set RDP Password'

                - powershell: |
                    $repoRoot = "${{ parameters.workingDirectory }}"
                    $privateKeyPath = "$(privateKey.secureFilePath)"
                    $publicKeyPath = "$(publicKey.secureFilePath)"
                    Copy-Item -Path $privateKeyPath -Destination "${{ parameters.workingDirectory }}\id_rsa" -Force
                    Copy-Item -Path $publicKeyPath -Destination "${{ parameters.workingDirectory }}\id_rsa.pub" -Force
                  displayName: "Copy SSH Keys"

                - task: TerraformInstaller@1
                  displayName: 'Install Terraform ${{ parameters.terraformVersion }}'
                  inputs:
                    terraformVersion: '${{ parameters.terraformVersion }}'

                - powershell: |
                    terraform init `
                      -backend-config="storage_account_name=$env:TF_STATE_BLOB_ACCOUNT_NAME" `
                      -backend-config="container_name=$env:TF_STATE_BLOB_CONTAINER_NAME" `
                      -backend-config="key=$env:TF_STATE_BLOB_FILE" `
                      -backend-config="sas_token=$env:TF_STATE_BLOB_SAS_TOKEN" -reconfigure -upgrade
                  displayName: 'Terraform Init'
                  workingDirectory: ${{ parameters.workingDirectory }}
                  env:
                    TF_STATE_BLOB_ACCOUNT_NAME: ${{ parameters.storageAccount }}
                    TF_STATE_BLOB_CONTAINER_NAME: ${{ parameters.storageContainer }}
                    TF_STATE_BLOB_FILE: ${{ parameters.stateFile }}
                    TF_STATE_BLOB_SAS_TOKEN: ${{ parameters.sasToken }}

                - powershell: |
                    cp $(Agent.BuildDirectory)/drop/main.tfplan main.tfplan
                  displayName: 'Copy Plan'
                  workingDirectory: ${{ parameters.workingDirectory }}

                - powershell: |
                    terraform apply -auto-approve main.tfplan
                  displayName: 'Terraform Apply'
                  workingDirectory: ${{ parameters.workingDirectory }}
                  env:
                    ARM_SUBSCRIPTION_ID: ${{ parameters.subscriptionId }}
                    ARM_CLIENT_ID: ${{ parameters.clientId }}
                    ARM_CLIENT_SECRET: ${{ parameters.clientSecret }}
                    ARM_TENANT_ID: ${{ parameters.tenantId }}

                - ${{ if eq(parameters.shouldUpdateDnsRecords, 'true') }}:
                  - task: PowerShell@2
                    displayName: 'Update DNS records'
                    inputs:
                      targetType: 'inline'
                      script: |
                        Install-Module -Name CloudflareDnsTools -Scope CurrentUser
                        .\Update-Cloudflare-Records.ps1
                      workingDirectory: ${{ parameters.workingDirectory }}
                      pwsh: true

                - ${{ if eq(parameters.shouldConfigureAlertManager, 'true') }}:
                  - task: PowerShell@2
                    displayName: 'Update DNS records'
                    inputs:
                      targetType: 'inline'
                      script: |
                        .\Configure-AlertManager.ps1
                      workingDirectory: ${{ parameters.workingDirectory }}
                      pwsh: true
